fromdate: "-7d"
todate: "now"
timezone: "America/Guatemala"
idproject: "1234567891"
apikey: "daf548ad5a10ad150d1ad2da3ddf5d5a1df10"
baseurl: "C:\\PATH\\TO\\FOLDER\\WITH\\FILESANDIMAGES\\"
stylesheets:
  - "css\\base.css"
  - "css\\tables.css"
  - "css\\simplegrid.css"
